[package]
name = "cluster_name_generator"
version = "0.1.0"
authors = ["Nate Gay <email@nategay.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

haikunator = "0.1.0"
